EMBED_DIM = 64
HIDDEN_DIM = 128
MAX_LENGTH = 30
INPUT_DIM = 28 # may change for language
OUTPUT_DIM = 62 # may change for language
BEAM_SIZE = 3

TYPE = 'LSTM'
ENCODER_NUM_LAYERS = 3
DECODER_NUM_LAYERS = 3
BATCH_FIRST = True
BATCH_SIZE = 64
DROPOUT_RATE = 0.2
BIDIRECTIONAL = True
EPOCHS = 40

PRINT_EVERY = 10
PLOT_EVERY = 100
LEARNING_RATE = 0.003
